### ISSUE TITLE
SVG icon issue

### ISSUE THREAD

**Issue by arincon9** [blocknotes/activeadmin_trumbowyg#2] opened 2017-11-22 22:16 UTC
I can't seem to get the SVG icons to show in Production.

Has anyone else encountered/ solved this issue?

Thank you!

**Comment by arincon9** [comment] 2017-11-23 19:13
Added an intermediary fix of rolling my own icons using font-awesome:

Added these lines to `active_admin.js.coffee`
```
$.trumbowyg.svgPath = false
$.trumbowyg.hideButtonTexts = true
```

Then overrode each icon's style like so:
```
.trumbowyg-superscript-button:after {
  font-family: FontAwesome;
  content: " \f12b";
}
```

**Comment by abpaul** [comment] 2017-11-27 19:32
@arincon9 I'm also in the same situation.
A temporary workaround is using `config.assets.compile = true` in `production.rb`, but I'd highly suggest not using it for a long period of time (or at all).

I tried precompiling the assets but the issue is still there. 
@blocknotes is this issue similar to what CKEditor has regarding the digested assets?

**Comment by arincon9** [comment] 2017-11-27 19:45
@paulbandrei Let me know if you need the css file for adding font-awesome icons. It has been working fine since implementing.

**Comment by abpaul** [comment] 2017-11-27 20:16
@arincon9 that would be great!
Could you put it in a gist?

**Comment by arincon9** [comment] 2017-11-27 20:23
@paulbandrei Here you go:
 https://gist.github.com/arincon9/5f9876e6116222287bc6bd24a4e22fca

Make sure to add:
```
$.trumbowyg.svgPath = false
$.trumbowyg.hideButtonTexts = true
```
to your `active_admin.js.coffee` file.

**Comment by blocknotes** [comment] 2017-12-02 10:02
Hi @arincon9 and @paulbandrei 
Ok... the problem here is that the SVG icons are loaded by trumbowyg via JS so I can't use the assets pipeline (easily).
I changed the font icon path and I added a rake task (`rake trumbowyg:nondigest`) that make a copy of the font icon without the digest fingerprint (it's a workaround but ok for now... the same thing that do ckeditor), which must be executed after every deploy.
The gem is updated (0.1.3).
Could you make some tests please?

**Comment by blocknotes** [comment] 2018-02-18 08:00
If anyone has feedback on this issue it would help

**Comment by blocknotes** [comment] 2018-11-03 17:02
No feedback - I close this one

**Closed as completed by blocknotes** 2018-11-03 17:02 UTC
